name: FeatureCI
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!gh_pages'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Only on feature branches"
    - name: Run a multi-line script
      run: |
        echo "Only on feature branches"
