name: Stage

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}"
          usedocker: true
          docker_build_args: |
            HUGO_WATCH
            HUGO_THEME
            HUGO_BASEURL
        env:
          HUGO_WATCH: true
          HUGO_THEME: "hugo-theme-console"
          HUGO_BASEURL: ${{secrets.HEROKU_BASEURL}}
